#!/usr/bin/env php

<?php

if (count($argv) >= 3 && $argv[2] === 'message') {
	$message = trim(file_get_contents($argv[1]));

	if (($index = strpos($message, '[ci]')) !== false) {
		$message = sprintf('%s %s', trim(substr($message, 0, $index)), trim(substr($message, $index + 4)));
	} else {
		$message = sprintf('%s [ci skip]', $message);
	}

	file_put_contents($argv[1], trim($message));
}
