#!/bin/bash

if [[ $# == 0 ]]; then
	printf "Usage: build <version>\n"
	exit 1
fi

git checkout --quiet releases || exit 1
git checkout --quiet BetterUpdating

version=$1

# Check to see if the version is unique
existingTag=$(git tag -l | grep "^$version$")

if [[ $existingTag != "" ]]; then
	printf "That version already exists.\n"
	exit 1
fi

# Add the tag for the version and build the release
git tag $version
./box build
mv raven.phar raven

git checkout --quiet releases

# Add the new release to the releases folder
cp raven releases/raven-$version
git add releases/raven-$version

# Add the new release information to the manifest file
name='raven.phar'
sha=$(openssl sha1 raven | awk '{ print $2 }')
url="raven-$version"

# Add the new release info to the manifest file
php -r "file_put_contents('manifest.json', json_encode(array_merge(json_decode(file_get_contents(\"manifest.json\"), true), [[\"name\" => \"$name\", \"sha1\" => \"$sha\", \"url\" => \"$url\", \"version\" => \"$version\"]]), JSON_PRETTY_PRINT));"
git add manifest.json

git commit -m "Built version $version of raven"

git checkout --quiet BetterUpdating

# Promt for deployment
read -p "Would you like to deploy this release?[y/n] " -n 1 -r input
printf "\n"

if [[ $input =~ ^[Yy]$ ]]
then
	printf "Deploying raven-$version\n"
	git push origin releases
	git push origin $version
	printf "Completed\n"
fi
