#!/bin/bash

echo " --------------- Download JDK 8.... --------------- "
cd /opt/; sudo wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u73-b02/jdk-8u73-linux-x64.tar.gz"
sudo tar xzf jdk-8u73-linux-x64.tar.gz
sudo rm -rf jdk-8u73-linux-x64.tar.gz
cd /opt/jdk1.8.0_73/

echo " --------------- Install JDK 8 and check the version.... --------------- "
sudo alternatives --install /usr/bin/java java /opt/jdk1.8.0_73/bin/java 2
java -version

echo " --------------- Download and Install Elastic Search 2.2.... --------------- "
cd ~; sudo wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.0/elasticsearch-2.2.0.tar.gz
tar -xvf elasticsearch-2.2.0.tar.gz
rm -rf elasticsearch-2.2.0.tar.gz

echo " --------------- Setup localhost for Elastic Search 2.2.... --------------- "
cd elasticsearch-2.2.0/config
echo "network.host: 0.0.0.0" >> elasticsearch.yml

echo " --------------- Download and Install Kibana.... --------------- "
cd ~; wget https://download.elastic.co/kibana/kibana/kibana-4.4.0-linux-x64.tar.gz
tar xvf kibana-4.4.0-linux-x64.tar.gz
rm -rf kibana-4.4.0-linux-x64.tar.gz

echo " --------------- Install Timelion, Marvel and Sense Kibana plugins.... --------------- "
cd kibana-4.4.0-linux-x64
./bin/kibana plugin --install kibana/timelion
./bin/kibana plugin --install elasticsearch/marvel/latest
./bin/kibana plugin --install elastic/sense

echo " --------------- Download and Install Logstash.... --------------- "
cd ~; wget https://download.elastic.co/logstash/logstash/logstash-2.2.0.tar.gz
tar xvf logstash-2.2.0.tar.gz
rm -rf logstash-2.2.0.tar.gz
