#!/bin/bash

echo " --------------- Installing dependencies.... --------------- "
sudo yum install -y centos-release-SCL
sudo yum install -y ruby193
sudo yum install -y ruby193-ruby-devel.x86_64
sudo yum install -y gcc
sudo yum install -y gcc-c++
echo " --------------- Enable ruby.... --------------- "
source /opt/rh/ruby193/enable
echo "source /opt/rh/ruby193/enable" | sudo tee -a /etc/profile.d/ruby193.sh
ruby -v
gem -v
echo " --------------- Installing mailcatcher.... --------------- "
gem install mailcatcher
