#!/bin/bash

echo " --------------- Installing dependencies.... --------------- "
sudo yum install -y centos-release-SCL
sudo yum install -y ruby200
sudo yum install -y ruby200-ruby-devel.x86_64
sudo yum install -y gcc
sudo yum install -y gcc-c++
echo " --------------- Enable ruby.... --------------- "
source /opt/rh/ruby200/enable
echo "source /opt/rh/ruby200/enable" | sudo tee -a /etc/profile.d/ruby200.sh
ruby -v
gem -v
echo " --------------- Installing mailcatcher.... --------------- "
gem install mailcatcher
