#!/usr/bin/env bash

# Installs and configures xdebug
if [ "$EUID" -ne 0 ]
	then echo "Please run as root"
	exit
fi

if [ ! -e "/etc/php.d/xdebug.ini" ]; then
	echo " --------------- Installing dependencies.... --------------- "
	sudo yum install -y php56w-devel php56w-pear gcc gcc-c++ autoconf automake
	echo " --------------- Installing xdebug.... --------------- "
	sudo pecl install Xdebug
	echo " ------------ Configuring xdebug... ------------ "
	sudo touch /etc/php.d/xdebug.ini
	sudo echo "[xdebug]" >> /etc/php.d/xdebug.ini
	sudo echo "zend_extension='/usr/lib64/php/modules/xdebug.so'" >> /etc/php.d/xdebug.ini
	sudo echo "xdebug.remote_enable = 1" >> /etc/php.d/xdebug.ini
        sudo echo "xdebug.remote_connect_back = 1" >> /etc/php.d/xdebug.ini
        sudo echo "xdebug.remote_port = 9000" >> /etc/php.d/xdebug.ini
        sudo echo "xdebug.remote_handler = dbgp" >> /etc/php.d/xdebug.ini
        sudo echo "xdebug.remote_mode = req" >> /etc/php.d/xdebug.ini
        sudo echo "xdebug.remote_autostart = true" >> /etc/php.d/xdebug.ini
	echo " ------------ Restarting apache... ------------ "
	sudo service httpd restart
fi
